export const MODULES = [
  {
    id: "honorarios",
    icon: "📐",
    label: "Honorarios",
    title: "Calculadora de Honorarios",
    desc: "Define tus tarifas en UF por m² para cada servicio. Recepción y levantamiento se calculan automáticamente como factor del Permiso de Edificación. Incluye renders, mobiliario personalizado y bundles de producción.",
    chips: ["✓ 5 servicios", "✓ UF + CLP", "✓ Renders", "✓ Mobiliario"],
  },
  {
    id: "presupuestos",
    icon: "📋",
    label: "Presupuestos",
    title: "Presupuestos profesionales",
    desc: "Crea y edita presupuestos completos con materiales, mano de obra y partidas personalizadas. Aplica márgenes y genera documentos listos para presentar al cliente.",
    chips: ["✓ Partidas", "✓ Márgenes", "✓ Materiales", "✓ Ilimitados en Plus"],
  },
  {
    id: "proyectos",
    icon: "🗂️",
    label: "Proyectos",
    title: "Control de Proyectos",
    desc: "Registra el avance de cada proyecto por etapas. Vincula presupuestos, clientes y documentos. Ten siempre claro qué está pendiente, en curso y terminado.",
    chips: ["✓ Etapas", "✓ Documentos", "✓ Estado"],
  },
  {
    id: "finanzas",
    icon: "💰",
    label: "Finanzas",
    title: "Control de Finanzas",
    desc: "Registra ingresos y egresos por proyecto. Visualiza el flujo financiero de tu estudio y controla lo cobrado versus lo pendiente.",
    chips: ["✓ Ingresos", "✓ Egresos", "✓ Por proyecto"],
  },
  {
    id: "clientes",
    icon: "👥",
    label: "Clientes",
    title: "Registro de Clientes y Proveedores",
    desc: "Centraliza el directorio de contactos. Vincula clientes a proyectos y registra proveedores con sus productos habituales.",
    chips: ["✓ Clientes", "✓ Proveedores", "✓ Vinculado a proyectos"],
  },
  {
    id: "pdf",
    icon: "📄",
    label: "PDF",
    title: "Exportación a PDF",
    desc: "Genera presupuestos y cotizaciones en PDF con tu nombre o logo, listos para enviar al cliente. Formato profesional con detalle de partidas y totales.",
    chips: ["✓ Diseño profesional", "✓ Logo propio", "✓ Plan Plus y Premium"],
  },
  {
    id: "ia",
    icon: "🤖",
    label: "Asistente IA",
    title: "Asistente IA",
    desc: "Busca automáticamente las últimas ofertas y productos nuevos en las páginas de tus proveedores favoritos. Siempre actualizado sin tener que revisar cada sitio manualmente.",
    chips: ["✓ Multi-proveedor", "✓ Precios actualizados", "✓ Solo Premium"],
  },
  {
    id: "escaneo",
    icon: "📷",
    label: "Escaneo",
    title: "Escaneo de Imágenes",
    desc: "Fotografía o sube pantallazos con productos y precios. La IA reconoce los artículos y los ingresa automáticamente a tu presupuesto. Ideal para catálogos y cotizaciones de proveedores.",
    chips: ["✓ OCR inteligente", "✓ Ingreso automático", "✓ Solo Premium"],
  },
  {
    id: "cuestionario",
    icon: "📝",
    label: "Cuestionario",
    title: "Cuestionario de Cliente",
    desc: "Crea un cuestionario personalizado con hasta 10 preguntas. Descárgalo como HTML y envíaselo al cliente. El cliente lo responde y genera un link — la IA guarda todo en tu base de datos automáticamente.",
    chips: ["✓ 10 preguntas editables", "✓ HTML descargable", "✓ Link de respuesta", "✓ IA guarda en tu BD"],
  },
];

export const PLANS = [
  {
    id: "free",
    name: "Free",
    price: "$0",
    period: "",
    features: ["3 cotizaciones", "Calculadora de tarifas", "Sin exportar", "Sin IA"],
    popular: false,
    btnVariant: "dim",
    btnLabel: "Empezar →",
  },
  {
    id: "plus",
    name: "Plus",
    price: "$9",
    period: "/mes",
    features: ["Cotizaciones ilimitadas", "Exportar a PDF", "Control de obras", "Gestión financiera", "Directorio de contactos"],
    popular: true,
    btnVariant: "primary",
    btnLabel: "Elegir Plus →",
  },
  {
    id: "premium",
    name: "Premium",
    price: "$19",
    period: "/mes",
    features: ["Todo lo de Plus", "IA integrada", "Lectura de imágenes", "Formulario inteligente"],
    popular: false,
    btnVariant: "outline",
    btnLabel: "Elegir Premium →",
  },
];
